set nocompatible
filetype off

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

Plug 'hashivim/vim-terraform'
Plug 'mustache/vim-mustache-handlebars'

call plug#end()

filetype plugin indent on

inoremap jk <ESC>

set backspace=indent,eol,start

set wildmenu
set noesckeys
set timeout timeoutlen=200

set smartindent
set autoindent

set number
set nowrap

set tabstop=2 shiftwidth=2 expandtab

let g:terraform_fmt_on_save=1
